[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "d1"
path = "src/d1.rs"

[[bin]]
name = "d6"
path = "src/d6.rs"

[dependencies]
regex = "1.10.2"
regex-macro = "0.2.0"
